version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - run:
          name: Generate .env file
          command: echo 'API_ENDPOINT='$API_ENDPOINT_STAGING > .env.js

      - restore_cache:
          key: yarn-v1-{{ checksum "package.json" }}

      - run:
          name: Install npm packages
          command: yarn

      - save_cache:
          key: yarn-v1-{{ checksum "package.json" }}
          paths:
          - node_modules

      - run:
          name: Run tests
          command: yarn run test
