version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:latest_broweres
    steps:
      - checkout
      - run:
        name: Generate .env file
        command: echo 'API_ENDPOINT='$API_ENDPOINT_STAGING > .env
      - restore_cache:
          key: v1-node_modules
      - run:
          name: Install npm packages
          command: yarn
      - save_cache:
          key: v1-node_modules
          paths:
          - node_modules
      - run:
          name: Run tests
          command: yarn test
