// book
export const GET_BOOKS = 'GET_BOOKS';
export const GET_BOOK = 'GET_BOOK';
// tag
export const GET_TAGS = 'GET_TAGS';
export const TOGGLE_CHOSEN = 'TOGGLE_CHOSEN';
// loading
export const REQUEST_API = 'REQUEST_API';
export const REQUEST_API_SUCCESS = 'REQUEST_API_SUCCESS';
export const REQUEST_API_FAIL = 'REQUEST_API_FAIL';
// scan
export const PERMISSIONS_DENIED = 'PERMISSIONS_DENIED';
export const PERMISSIONS_GRANTED = 'PERMISSIONS_GRANTED';
export const READING_JANCODE = 'READING_JANCODE';
export const VALID_JANCODE = 'VALID_JANCODE';
export const INVALID_JANCODE = 'INVALID_JANCODE';
// form
export const CHANGE_TITLE = 'CHANGE_TITLE';
export const CHOOSE_DATE = 'CHOOSE_DATE';
export const CHOOSE_PHOTO = 'CHOOSE_PHOTO';
export const TOGGLE_DATETIME_PICKER = 'TOGGLE_DATETIME_PICKER';
export const VALIDATE_TITLE = 'VALIDATE_TITLE';
